server:
  port: 8082
spring:
  application:
    name: feign

eureka:
  client:
    #eureka服务地址
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:
    #开启断路器
    enabled: true