server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/four
    username: root
    password: zzy12345
  application:
    name: provider
  data:
    redis:
      database: 0
      host: 127.0.0.1
      post: 6379
      password:
    mongodb:
      uri: mongodb://localhost:27017/zzy
    #配置elasticSearch信息
    elasticsearch:
      #连接的集群名称
      cluster-name: elasticsearch
      #连接的集群节点
      cluster-nodes: localhost:9300
      #是否开启本地储存
      repositories:
        enabled: true
eureka:
  client:
    #eureka服务地址
    service-url:
      defaultZone: http://localhost:8080/eureka

mybatis:
  #mybatisxml文件的地址
  mapper-locations: classpath:mapper/*.xml
  #showsql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
