server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/20067
    username: root
    password: zzy12345
  application:
    name: provider
eureka:
  client:
    #eureka服务地址
    service-url:
      defaultZone: http://localhost:8080/eureka

mybatis:
  #mybatisxml文件的地址
  mapper-locations: classpath:mapper/*.xml
  #showsql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
